<# 
    Add hardware from a CSV file

    This sample shows how you can use Import-HardwareCsv to add and configure
    many cameras quickly.

    To use the sample, please login to your VMS with Connect-ManagementServer
    and consider changing which Recording Server the camera is added to. The
    first Recording Server returned by Get-RecordingServer will be used.

    The script below will first create a CSV file with a universal driver
    camera to use in the Import-HardwareCsv command. You would normally prepare
    your own CSV file instead. The CSV generated by this script will be placed
    in the current folder and will look like this:

    "HardwareName","HardwareAddress","DriverId","GroupPath"
    "Universal Driver","http://wowzaec2demo.streamlock.net","421","/New Cameras"
#>

$rows = @([pscustomobject]@{
    HardwareName = "Universal Driver"
    HardwareAddress = "http://wowzaec2demo.streamlock.net"
    DriverId = 421
    GroupPath = "/New Cameras"
})
$rows | Export-Csv .\test.csv -NoTypeInformation

